let movieData = [
  {
    id: 0,
    title: '아이언맨',
    directors: ['감독1'],
    scenarios: ['각본1', '각본2'],
    actors: ['배우1', '배우2', '배우3'],
    registrant: '작성자1',
    genres: ['공포', '멜로'],
    tags: ['부산대학교'],
    date: '2022-04-07',
  },
  {
    id: 1,
    title: '기생충',
    directors: ['감독2'],
    scenarios: ['각본3', '각본4'],
    actors: ['배우4', '배우5', '배우6'],
    registrant: '작성자2',
    genres: ['액션', '스릴러'],
    tags: ['인기영화', '경성대학교'],
    date: '2023-01-02',
  },
  {
    id: 2,
    title: '가문의 영광',
    directors: ['감독3','감독4'],
    scenarios: ['각본5', '각본6'],
    actors: ['배우1', '배우7', '배우8'],
    registrant: '작성자3',
    genres: ['판타지'],
    tags: ['동의대학교'],
    date: '2022-11-29',
  },
  {
    id: 3,
    title: '아바타',
    directors: ['감독5'],
    scenarios: ['각본7', '각본8'],
    actors: ['배우4', '배우9', '배우10'],
    registrant: '작성자4',
    genres: ['멜로'],
    tags: ['동의대학교'],
    date: '2022-10-15',
  },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
  // {
  //   id: ,
  //   title: '',
  //   directors: ['감독'],
  //   scenarios: ['각본', '각본'],
  //   actors: ['배우', '배우', '배우'],
  //   registrant: '작성자',
  //   genres: [],
  //   tags: [],
  //   date: '',
  // },
]

export default movieData;